application_port: 3000
database:
  host: '127.0.0.1'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database_name: 'hummus'
  require_ssl: false
redis:
  host: '127.0.0.1'
  port: 6379
  secret_key: 686eGO13G4SGIxWORMgKYgLaasXCKW0oJI8DYgLstmYhWIQxnWuKfGzazkhHZc46FPZmqQnOHAgwb+998Vwc1A==
sentry_dsn: https://33db4f8bf30c4e6c8636808eed112d79@o1172026.ingest.sentry.io/6497424
frontend_url: http://localhost:3001
email_client:
  base_url: https://api.postmarkapp.com
  sender_email: peter.leeh@bitgap.com
  authorization_token: b40d6f26-c6f7-4f90-9381-b5f26579e2f9
  timeout_milliseconds: 10000
meili:
  url: http://localhost:7700
  master_key: SUPER_SECRET_KEY
oauth:
  discord:
    client_id: 997545848957313054
    client_secret: JR9XG-8qR1D8JhuNEV-3-Df1p-013_ap
    redirect_url: http://localhost:3001/auth/discord_authorize
    auth_url: https://discord.com/api/oauth2/authorize?response_type=code
    token_url: https://discord.com/api/oauth2/token
    revocation_url: https://discord.com/api/oauth2/token/revoke
  google:
    client_id: 193420761201-v858oknq8mfaps3l262njru2j0o776qg.apps.googleusercontent.com
    client_secret: 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
    redirect_url: http://localhost:3001/auth/google_authorize
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    token_url: https://www.googleapis.com/oauth2/v3/token
    revocation_url: https://oauth2.googleapis.com/revoke
